---
hypervisor_script: build/tinyrange_qemu.star
# Download from: https://github.com/tinyrange/linux_build/releases/download/linux_x86_6.6.7/vmlinux_x86_64 
kernel_filename: local/vmlinux_x86_64
cpu_cores: 1
memory_mb: 1
storage_size: 1024
rootfs_fragments:
      - builtin:
              name: init
              guest_filename: /init
      - builtin:
              name: init.star
              guest_filename: /init.star
      - oci_image:
              image_name: library/alpine:latest
