schema = 3

[mod]
  [mod."dario.cat/mergo"]
    version = "v1.0.0"
    hash = "sha256-jlpc8dDj+DmiOU4gEawBu8poJJj9My0s9Mvuk9oS8ww="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v0.0.0-20230828082145-3c4c8a2d2371"
    hash = "sha256-YxAaQgQoTOhD8hE+aT+T8ytKKxcQW6tgoL2MAU7nTvo="
  [mod."github.com/basgys/goxml2json"]
    version = "v1.1.0"
    hash = "sha256-WvL4MPRqjxTYy7GdSVGfszyQpameRUtp7609zcoHGK4="
  [mod."github.com/bitly/go-simplejson"]
    version = "v0.5.1"
    hash = "sha256-ypd4SyAww1+1IlxXlAeGYbTKwl/mahlj9k0MjXJkAJ0="
  [mod."github.com/blakesmith/ar"]
    version = "v0.0.0-20190502131153-809d4375e1fb"
    hash = "sha256-AV5UX5EvE14WFdaDOYtNG1N+MW6v8N/7KIulRQCb3QE="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/cloudflare/circl"]
    version = "v1.3.3"
    hash = "sha256-ItdVkU53Ep01553/tJ4MdAwoTpPljRxiBW9sAd7p0xI="
  [mod."github.com/cyphar/filepath-securejoin"]
    version = "v0.2.4"
    hash = "sha256-heCD0xMxlwnHCHcRBgTjVexHOLyWI2zRW3E8NFKoLzk="
  [mod."github.com/emirpasic/gods"]
    version = "v1.18.1"
    hash = "sha256-hGDKddjLj+5dn2woHtXKUdd49/3xdsqnhx7VEdCu1m4="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.1-0.20230307220236-3a3c6141e376"
    hash = "sha256-f4k0gSYuo0/q3WOoTxl2eFaj7WZpdz29ih6CKc8Ude8="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.5.0"
    hash = "sha256-4XUoD2bOCMCdu83egb/y8kY/Fm0s1rWgPMtiahh38OQ="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.11.0"
    hash = "sha256-2yUM/FlV+nYxacVynJCnDZeMub4Iu8JL2WBHmlnwOkE="
  [mod."github.com/go-python/gpython"]
    version = "v0.2.0"
    hash = "sha256-m4WP/PI/B7xDOohMo5s9sLMGXSq3HOWX2fjLTVFdBGw="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/icza/dyno"]
    version = "v0.0.0-20230330125955-09f820a8d9c0"
    hash = "sha256-PnXvbfwzNx8dksqU/LAy1InD/YcEaesFsnpUnW7iEvg="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/kevinburke/ssh_config"]
    version = "v1.2.0"
    hash = "sha256-Ta7ZOmyX8gG5tzWbY2oES70EJPfI90U7CIJS9EAce0s="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.7"
    hash = "sha256-UkW+tAFEZYj067z9gXDQjQx0dCF8noCn5OSw/APh4oo="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.0.9"
    hash = "sha256-0rHlHzEVaDdkVbRJDhnAJjfJUmAHOYjXN5u7VoCi5uk="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.0"
    hash = "sha256-oEo/BoMqSLdwSjrhHTiFjl5Om4MVLNQXDJINk6Z110Y="
  [mod."github.com/mitchellh/colorstring"]
    version = "v0.0.0-20190213212951-d06e56a500db"
    hash = "sha256-dg5havre+NkxU85tbWXgdhjVtVnkNfTVa999HX+JVbQ="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.1"
    hash = "sha256-RWyw05s4Wnz44J2YzPkJAK/A4l5V4ZGk/c2I4lW18wc="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.6"
    hash = "sha256-QlY6AzrSB/8IrlINPi8J8uw1J0SOa2UMTtlo79fg9gM="
  [mod."github.com/nix-community/go-nix"]
    version = "v0.0.0-20231219074122-93cb24a86856"
    hash = "sha256-gCRU9d4tuGP70i2IA2pl+ZcowHrWfN4mdOnQQR7AnH4="
  [mod."github.com/pjbgf/sha1cd"]
    version = "v0.3.0"
    hash = "sha256-kX9BdLh2dxtGNaDvc24NORO+C0AZ7JzbrXrtecCdB7w="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/schollz/progressbar/v3"]
    version = "v3.14.2"
    hash = "sha256-LgnZfRlsCOoTs4s+kgBj4wM93mlUQ7vzH8Jru/lBpyQ="
  [mod."github.com/sergi/go-diff"]
    version = "v1.1.0"
    hash = "sha256-8NJMabldpf40uwQN20T6QXx5KORDibCBJL02KD661xY="
  [mod."github.com/skeema/knownhosts"]
    version = "v1.2.1"
    hash = "sha256-u0jB6ahTdGa+SvcIvPNRLnbSHvgmW9X/ThRq0nWQrJs="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/xanzy/ssh-agent"]
    version = "v0.3.3"
    hash = "sha256-l3pGB6IdzcPA/HLk93sSN6NM2pKPy+bVOoacR5RC2+c="
  [mod."github.com/xi2/xz"]
    version = "v0.0.0-20171230120015-48954b6210f8"
    hash = "sha256-2J4cb9KUnGHn1WZ2+g/S+yiHGLDt6KU0cP3fJpQDGZ0="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.9"
    hash = "sha256-98cKiMZcxl11laO3IiRHnhSgh7mEjl0iKlPxsSPdbww="
  [mod."go.starlark.net"]
    version = "v0.0.0-20240314022150-ee8ed142361c"
    hash = "sha256-dXCzSYXMOMEavQIJEzi5OsJWGnuU751ONBwCUjLPvGw="
  [mod."golang.org/x/crypto"]
    version = "v0.21.0"
    hash = "sha256-Z4k1LvFh4Jai7HUe6TTuXSG3VnuiRpMwdARIdZZqSYk="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240318143956-a85f2c67cd81"
    hash = "sha256-HjEmpjgXqIuGc5rsTVkg6OPAN2fGhfkska7cwRu1qaw="
  [mod."golang.org/x/mod"]
    version = "v0.16.0"
    hash = "sha256-aN1Cz5Wqd9YCjK8nFW6JWn+n1HfFoEcgYZmGO/FYtbw="
  [mod."golang.org/x/net"]
    version = "v0.22.0"
    hash = "sha256-pcefO4noO9I6mATKBWF6shgIjZvFg0kDsV1Jo/NsFns="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/term"]
    version = "v0.18.0"
    hash = "sha256-lpze9arFZIhBV8Ht3VZyoiUwqPkeH2IwfXt8M3xljiM="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/tools"]
    version = "v0.19.0"
    hash = "sha256-Xf05Ao398gBzxn5C8H6x+XsLjFLIm+UUfpDekQYA0cw="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.1"
    hash = "sha256-aXTwU+4m3JBjdX81Tw6MM8u4d39aoUICwP0g2ersmb0="
  [mod."lukechampine.com/blake3"]
    version = "v1.1.6"
    hash = "sha256-pKVTpuCcqGSn8s11Jq33yrXewQLvycuAoxKJEdbZ7rA="
  [mod."mvdan.cc/sh/v3"]
    version = "v3.8.0"
    hash = "sha256-MJvF/6uC5eGKk4po2syUk4d4tKKSOe++xmR2znxVb5s="
