# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["alpha"]
  pull_request:
    branches: ["alpha"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Build
        run: |
          go run ./tools/build.go -os linux -arch amd64

      - name: Install QEMU
        run: |
          sudo apt-get install -y qemu-kvm

      - name: Run Test
        run: |
          ./build/tinyrange login -E "whoami"
