# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["alpha"]
  pull_request:
    branches: ["alpha"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Build
        run: |
          go run ./build.go -os linux -arch amd64
          go run ./build.go -os windows -arch amd64

      - uses: actions/upload-artifact@v4
        with:
          name: tinyrange_installer_linux_amd64
          path: build/tinyrange_installer_linux_amd64

      - uses: actions/upload-artifact@v4
        with:
          name: tinyrange_installer_windows_amd64
          path: build/cross-windows-amd64/tinyrange_installer_windows_amd64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: tinyrange_qemu.star
          path: build/tinyrange_qemu.star
